### Signup route
POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
    "email": "onyango9088@gmail.com",
    "password": "@Software23"
}

### Signin endpoint
POST http://localhost:5001/api/auth/signin
Content-Type: application/json

{
    "email": "onyango9088@gmail.com",
    "password": "@Software23"
}

### Signout
POST http://localhost:5001/api/auth/signout

### Sending verification code
PATCH  http://localhost:5001/api/auth/send-verification-code
Content-Type: application/json

{
    "email": "onyango9088@gmail.com"
}